# Generated by Django 4.2.1 on 2023-07-03 12:35

import django.core.validators
from django.db import migrations, models
import petstagram.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), petstagram.accounts.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='petstagramuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='petstagramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), petstagram.accounts.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
